/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import kelas.Item;
import popUp.PopUp_Item;
import static popUp.PopUp_Item.cKategor;
import static popUp.PopUp_Item.cLemari;
import static popUp.PopUp_Item.tNamaBarang;
import static popUp.PopUp_Item.tPenulis;
import static popUp.PopUp_Item.tTahunTerbit;
import static popUp.PopUp_Item.tJumlah;

import static popUp.PopUp_Item.Lb_item;

/**
 *
 * @author WINDOWS 10
 */
public class menuItem extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public menuItem() {
        initComponents();
        loadTable();
    }
    
     void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id item");
        model.addColumn("kategori");
        model.addColumn("lemari");
        model.addColumn("nama barang");
        model.addColumn("penulis");
        model.addColumn("tahun terbit");
        model.addColumn("jumlah");
        
        try {
            Item it = new Item();
            ResultSet data = it.tampilItem();
                       while (data.next()) {
                model.addRow(new Object[]{
                    data.getInt("id_item"),
                    data.getString("kategori"),
                    data.getString("lemari"),
                    data.getString("nama_barang"),
                    data.getString("penulis"),
                    data.getString("tahun_terbit"),
                    data.getString("jumlah"),});
                    
                       }


        } catch (SQLException sQLException) {
        }
        tItem.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tItem = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 125, 197));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/add.png"))); // NOI18N
        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tItem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            PopUp_Item pp = new PopUp_Item();
            pp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tItemMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int baris = tItem.rowAtPoint(evt.getPoint());
            String id_itemp = tItem.getValueAt(baris, 0).toString();
            String kategori = tItem.getValueAt(baris, 1).toString();
            String lemari = tItem.getValueAt(baris, 2).toString();
            String nama_barang = tItem.getValueAt(baris, 3).toString();
            String penulis = tItem.getValueAt(baris, 4).toString();
            String tahun_terbit = tItem.getValueAt(baris, 5).toString();
            String jumlah = tItem.getValueAt(baris, 6).toString();
           
            PopUp_Item item = new PopUp_Item();
            
            Lb_item.setText(id_itemp);
            
            cKategor.setToolTipText(kategori);
            cLemari.setToolTipText(lemari);
            tNamaBarang.setText(nama_barang);
            tPenulis.setText(penulis);
            tTahunTerbit.setText(tahun_terbit);

            
            item.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tItemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tItem;
    // End of variables declaration//GEN-END:variables
}
