/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import kelas.Peminjaman;
import popUp.PopUp_Peminjaman;
import static popUp.PopUp_Peminjaman.id_peminjaman;
import static popUp.PopUp_Peminjaman.tJudul;
import static popUp.PopUp_Peminjaman.tJumlahPinjam;
import static popUp.PopUp_Peminjaman.tKode;
import static popUp.PopUp_Peminjaman.tNamaBarang;
import static popUp.PopUp_Peminjaman.tNamaPeminjam;
import static popUp.PopUp_Peminjaman.tNimNidn;
import static popUp.PopUp_Peminjaman.tPinjam;

/**
 *
 * @author WINDOWS 10
 */
public class menuPeminjaman extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public menuPeminjaman() {
        initComponents();
        loadTable();

    }

    void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id peminjam");
        model.addColumn("tanggal pinjam");
        model.addColumn("tanggal kembali");
        model.addColumn("nim/nidn");
        model.addColumn("nama peminjam");
        model.addColumn("kode barang");
        model.addColumn("nama barang");
        model.addColumn("judul");
        model.addColumn("jumlah peminjam");
        model.addColumn("status");

        try {
            Peminjaman pj = new Peminjaman();
            ResultSet data = pj.tampilPeminjaman();
            
            java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd MMMM yyyy", new java.util.Locale("id", "ID"));

            while (data.next()) {
                //format tanggl
                String formattedDateTanggalpinjam = "";
                if (data.getString("tanggal_pinjam") != null) {
                    java.util.Date date = java.sql.Date.valueOf(data.getString("tanggal_pinjam"));
                    formattedDateTanggalpinjam = dateFormat.format(date);
                }
                String formattedDateTanggalkembali = "";
                if (data.getString("tanggal_kembali") != null) {
                    java.util.Date date = java.sql.Date.valueOf(data.getString("tanggal_kembali"));
                    formattedDateTanggalkembali = dateFormat.format(date);
                }
                model.addRow(new Object[]{
                    data.getString("id_peminjam"),
                    formattedDateTanggalpinjam,
                    formattedDateTanggalkembali,
                    data.getString("nim_nidn"),
                    data.getString("nama_peminjam"),
                    data.getString("kode_barang"),
                    data.getString("nama_barang"),
                    data.getString("judul"),
                    data.getString("jumlah_pinjam"),
                    data.getString("status"),});

            }

        } catch (SQLException sQLException) {
        }
        tPeminjaman.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPeminjaman = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/add.png"))); // NOI18N
        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tPeminjaman);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6076, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            PopUp_Peminjaman pp = new PopUp_Peminjaman();
            pp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPeminjamanMouseClicked
        try {
            // TODO add your handling code here:
            int baris = tPeminjaman.rowAtPoint(evt.getPoint());
            String id_pemiinjam = tPeminjaman.getValueAt(baris, 0).toString();
            String tgl_peminjam = tPeminjaman.getValueAt(baris, 1).toString();
            String tgl_kembali = tPeminjaman.getValueAt(baris, 2).toString();
            String nomor_induk = tPeminjaman.getValueAt(baris, 3).toString();
            String nama_peminjam = tPeminjaman.getValueAt(baris, 4).toString();
            String kode_barang = tPeminjaman.getValueAt(baris, 5).toString();
            String nama_barang = tPeminjaman.getValueAt(baris, 6).toString();
            String judul = tPeminjaman.getValueAt(baris, 7).toString();
            String jumlah_pinjam = tPeminjaman.getValueAt(baris, 8).toString();
           // String status = tPeminjaman.getValueAt(baris, 9).toString();
            
            PopUp_Peminjaman pinjam = new PopUp_Peminjaman();
            
            id_peminjaman.setText(id_pemiinjam);
            // Konversi tanggal dari format "dd MMMM yyyy" ke "java.util.Date"
            if (tgl_peminjam != null && !tgl_peminjam.isEmpty()) {
                try {
                    java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("dd MMMM yyyy", new java.util.Locale("id", "ID"));
                    java.util.Date date = formatter.parse(tgl_peminjam);
                    tPinjam.setDate(date);
                } catch (ParseException ex) {
                    Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            tNamaPeminjam.setText(nama_peminjam);
            tKode.setText(kode_barang);
            tNamaBarang.setText(nama_barang);
            tJudul.setText(judul);
            tJumlahPinjam.setText(jumlah_pinjam);
//            PopUp_Peminjaman.tStatus.setSelectedItem(status);
            
            pinjam.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_tPeminjamanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPeminjaman;
    // End of variables declaration//GEN-END:variables
}
