/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import kelas.Anggota;
import popUp.PopUp_Anggota;
import static popUp.PopUp_Anggota.tNama;
import static popUp.PopUp_Anggota.tAlamat;
import static popUp.PopUp_Anggota.tNoHp;
import static popUp.PopUp_Anggota.tEmail;
import static popUp.PopUp_Anggota.lb_Id;
import static popUp.PopUp_Anggota.tNimNidn;

/**
 *
 * @author WINDOWS 10
 */
public class menuAnggota extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public menuAnggota() {
        initComponents();
        loadTable();
    }
    
    void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id_Anggota");
        model.addColumn("nama");
        model.addColumn("alamat");
        model.addColumn("nohp");
        model.addColumn("email");
        model.addColumn("nim_nidn");
        
        try {
            Anggota pj = new Anggota();
            ResultSet data = pj.tampilAnggota();
                       while (data.next()) {
                model.addRow(new Object[]{
                    data.getInt("id_anggota"),
                    data.getString("nama"),
                    data.getString("alamat"),
                    data.getString("nohp"),
                    data.getString("email"),
                    data.getString("nim_nidn"),});
                    
                       }


        } catch (SQLException sQLException) {
        }
        tAnggota.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAnggota = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 125, 197));

        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/add.png"))); // NOI18N
        bTambah.setText("TAMBAH");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        tAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tAnggota);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        try {
            PopUp_Anggota pp = new PopUp_Anggota();
            pp.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuAnggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void tAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tAnggotaMouseClicked
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            int baris = tAnggota.rowAtPoint(evt.getPoint());
            String id_Anggota = tAnggota.getValueAt(baris, 0).toString();
            String nama = tAnggota.getValueAt(baris, 1).toString();
            String alamat = tAnggota.getValueAt(baris, 2).toString();
            String nohp = tAnggota.getValueAt(baris, 3).toString();
            String email = tAnggota.getValueAt(baris, 4).toString();
            String nim_nidn = tAnggota.getValueAt(baris, 5).toString();
           
            PopUp_Anggota anggota = new PopUp_Anggota();
            
            lb_Id.setText(id_Anggota);
            // Konversi tanggal dari format "dd MMMM yyyy" ke "java.util.Date"
           
            tNama.setText(nama);
            tAlamat.setText(alamat);
            tNoHp.setText(nohp);
            tEmail.setText(email);
            tNimNidn.setText(nim_nidn);
//
            
            anggota.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(menuPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_tAnggotaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tAnggota;
    // End of variables declaration//GEN-END:variables
}
